@startuml

title: 自动更新阿里云OSS下Bucket自定义域名证书

start
:加载OSS配置;
repeat
while (待处理证书队列不为空?)
  :读取一项配置;
  if (获取OSS下Bucket自定义域名信息?) is (成功) then
    if (Bucket下是否存在自定义域名信息?) is (存在) then
      :获取域名证书CertId信息;
      if (判断域名证书是否已经失效 & 是否会在15天(默认，可配置)内过期?) is (是) then
              group 申请新证书
                if (申请新证书?) is (成功) then
                  :上传证书到证书管理服务;
                  :获取新域名的CertId信息;
                  fork
                    :更新Bucket下自定义域名证书绑定;
                  fork again
                    -[#hotpink,dashed]->
                    :更新(尝试)CDN下加速域名HTTPS证书绑定;
                    -[#hotpink,dashed]->
                  end merge
                  if (更新成功?) is (是) then
                    :发送成功通知;
                  else (否)
                    :发送失败通知;
                  endif
                else (失败)
                endif
                :继续;
              end group
            else (否)
              :继续;
            endif
    else (不存在)
    :继续;
    endif
  else (失败)
    :发送失败通知;
    :继续;
  endif
endwhile
repeat while(6小时之后)
stop

@enduml